try {
   var a;
} catch (error) {
    console.log(error);
        
}